version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    environment:
      GK_LOCK_DEFAULT_BRANCH: saga
    steps:
      - checkout

      - run:
          name: Install latest npm
          command: sudo npm install -g npm@

      - run:
          name: Install Greenkeeper
          command: sudo npm i -g greenkeeper-lockfile@2
      - run:
          name: Update lockfile
          command: npx greenkeeper-lockfile-update

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm ci --no-audit
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build App
          command: npm run build

      - run:
          when: on_success
          name: Publish to GitHub pages
          working_directory: build
          command: |
            git config --global user.email "circle-ci@example.com"
            git config --global user.name "CircleCI"
            git init
            git add -A
            git commit -m "Update build."
            git remote add origin https://github.com/bifravst/device-ui.git
            git push -f origin master:gh-pages

      - run:
          when: on_success
          name: Upload lockfile
          command: npx greenkeeper-lockfile-upload

      - run:
          when: on_success
          name: Run semantic relase
          command: |
            npm i semantic-release
            npx semantic-release || true

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: bifravst
