name: Test and Release

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install latest npm
        run: |
          sudo npm install -g npm@
          npm config set update-notifier false
      - name: Authenticate with NPM
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GH_TOKEN" > ~/.npmrc
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Build
        run: npm run build
      - name: Semantic release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm i --no-save semantic-release@next
          npx semantic-release
